# Generated by Django 3.1.7 on 2021-04-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
