# Generated by Django 3.1.7 on 2021-03-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('self', 'Самовывоз'), ('delivery1', 'Доставка в пункт выдачи'), ('delivery2', 'Почтовая доставка')], default=None, max_length=100, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Корзина'), ('new', 'Оформлен'), ('paid', 'Оплачен'), ('in_progress', 'В обработке'), ('is_ready', 'Готов'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен в место выдачи'), ('received', 'Получен'), ('completed', 'Завершен'), ('canceled', 'Отменен'), ('return', 'Возврат')], default='cart', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
