# Generated by Django 3.1.7 on 2021-03-19 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210319_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.product', verbose_name='Подарок'),
        ),
    ]
