# Generated by Django 3.1.7 on 2021-03-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210316_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('G', 'Для всех'), ('M', 'Для мужчин'), ('F', 'Для женщин')], default='G', max_length=1, verbose_name='Пол'),
        ),
    ]
