# Generated by Django 3.1.7 on 2021-03-31 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='content',
        ),
    ]
