# Generated by Django 3.1.7 on 2021-03-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('self', 'Самовывоз из мастерской (бесплатно)'), ('delivery_cdekspb', 'Доставка до пункта выдачи СДЭК по СПб'), ('delivery_spb', 'Курьерская доставка по СПб'), ('delivery_ru', 'Почтовая отправка по России'), ('delivery_world', 'Почтовая отправка за рубеж')], default=None, max_length=100, null=True, verbose_name='Тип заказа'),
        ),
    ]
