# Generated by Django 3.1.7 on 2021-03-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210313_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('self', 'Самовывоз'), ('delivery1', 'Доставка в пункт выдачи'), ('delivery2', 'Почтовая доставка')], default=None, max_length=100, null=True, verbose_name='Тип заказа'),
        ),
    ]
