# Generated by Django 3.1.7 on 2021-04-06 14:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210406_1702'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('carts', django.db.models.manager.Manager()),
            ],
        ),
    ]
