# Generated by Django 3.1.7 on 2021-03-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210319_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash_card', 'Наличные или банковская карта в мастерской'), ('bankcard', 'Банковская карта онлайн'), ('kiwi', 'Kiwi кошелёк / Paypal')], default=None, max_length=100, null=True, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Корзина'), ('new', 'Оформлен'), ('in_progress', 'В обработке'), ('is_ready', 'Готов'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен в место выдачи'), ('received', 'Получен'), ('return', 'Возврат'), ('canceled', 'Отменен')], default='cart', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
