# Generated by Django 3.1.7 on 2021-03-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_article_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(blank=True, default='_', max_length=50, verbose_name='Пункт меню'),
            preserve_default=False,
        ),
    ]
