# Generated by Django 3.1.7 on 2021-03-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210313_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': '[ 3. Изображения ]'},
        ),
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('self', 'Самовывоз из торгового центра'), ('delivery1', 'Доставка в пункт выдачи'), ('delivery2', 'Почтовая доставка')], default=None, max_length=100, null=True, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Корзина'), ('new', 'Оформлен'), ('paid', 'Оплачен'), ('in_progress', 'В обработке'), ('is_ready', 'Готов'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен в место выдачи'), ('received', 'Получен'), ('return', 'Возврат'), ('canceled', 'Отменен')], default='cart', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
