# Generated by Django 3.1.7 on 2021-03-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210316_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('bankcard', 'Оплата по карте онлайн'), ('kiwi', 'Киви кошелёк / пейпал')], default=None, max_length=100, null=True, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('self', 'Самовывоз из мастерской (бесплатно)'), ('deliveryspb', 'Курьерская доставка по СПб (450₽)'), ('deliveryru', 'Почтовая отправка по России (300₽)'), ('deliveryoutbound', 'Почтовая отправка за рубеж (600₽)')], default=None, max_length=100, null=True, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='шт'),
        ),
    ]
