# Generated by Django 3.1.7 on 2021-03-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210313_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': '[ 1. Заказы ]'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('subcategory', 'title'), 'verbose_name': 'Товар', 'verbose_name_plural': '[ 2. Товары ]'},
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_products',
            field=models.PositiveIntegerField(default=0, verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bestseller',
            field=models.BooleanField(default=False, verbose_name='Хит'),
        ),
        migrations.AlterField(
            model_name='product',
            name='visits',
            field=models.IntegerField(default=0, help_text='Количество просмотров', verbose_name='👁'),
        ),
    ]
