# Generated by Django 3.1.7 on 2021-03-19 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210319_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('self', 'Самовывоз из мастерской (бесплатно)'), ('deliveryspb', 'Курьерская доставка по СПб (450₽)'), ('deliveryru', 'Почтовая отправка по России (300₽)'), ('deliveryoutbound', 'Почтовая отправка за рубеж (600₽)')], default=None, max_length=100, null=True, verbose_name='Способ доставки')),
                ('delivery_cost', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость доставки')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='buying_type',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.delivery', verbose_name='Тип доставки'),
        ),
    ]
