# Generated by Django 3.1.8 on 2021-04-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210406_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='id платежа в Юkassa'),
        ),
    ]
