# Generated by Django 3.1.7 on 2021-04-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210403_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='meaning',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
