# Generated by Django 3.1.7 on 2021-03-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210319_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delivery_type',
            new_name='delivery_type_name',
        ),
    ]
