# Generated by Django 3.1.7 on 2021-04-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210403_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ('name',), 'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры'},
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='title',
        ),
        migrations.AddField(
            model_name='parameter',
            name='name',
            field=models.CharField(default='FREE_DELIVERY', max_length=255, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
