# Generated by Django 3.1.7 on 2021-03-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210314_0236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Сессия', 'verbose_name_plural': '[ Сессии ]'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='session',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Сессия клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
