# Generated by Django 3.1.7 on 2021-04-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210403_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.IntegerField(verbose_name='Значение'),
        ),
    ]
