# Generated by Django 3.1.7 on 2021-03-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210319_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('self', 'Самовывоз из мастерской (бесплатно)'), ('deliveryspb', 'Курьерская доставка по СПб (450₽)'), ('deliveryru', 'Почтовая отправка по России (300₽)'), ('deliveryoutbound', 'Почтовая отправка за рубеж (600₽)')], default=None, max_length=100, null=True, verbose_name='Тип заказа'),
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
