# Generated by Django 3.1.7 on 2021-03-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210319_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Стоимость доставки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('self', 'Самовывоз из мастерской (бесплатно)'), ('delivery_spb', 'Курьерская доставка по СПб (450₽)'), ('delivery_ru', 'Почтовая отправка по России (300₽)'), ('delivery_world', 'Почтовая отправка за рубеж (600₽)')], default=None, max_length=100, null=True, verbose_name='Тип заказа'),
        ),
    ]
