# Generated by Django 3.1.7 on 2021-03-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210319_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Трекинг номер'),
        ),
    ]
