# Generated by Django 3.1.7 on 2021-03-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20210319_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('self', 'Самовывоз из мастерской (бесплатно)'), ('delivery_spb', 'Курьерская доставка по СПб (450₽)'), ('delivery_ru', 'Почтовая отправка по России (300₽)'), ('delivery_world', 'Почтовая отправка за рубеж (600₽)')], default='self', max_length=100, verbose_name='Тип заказа'),
        ),
    ]
