# Generated by Django 3.1.7 on 2021-03-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210319_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('self', 'Самовывоз из мастерской (бесплатно)'), ('delivery_spb', 'Курьерская доставка по СПб'), ('delivery_ru', 'Почтовая отправка по России'), ('delivery_world', 'Почтовая отправка за рубеж')], default='self', max_length=100, verbose_name='Тип заказа'),
        ),
    ]
